name: 'Update Stonks'
description: 'Update Daily Stonks to your README.md'
inputs:
  crypto:
    description: 'Crypto'
    required: true
  days:
    description: 'Days of market'
    required: false
    default: '5'
  weather-api-key:
    description: 'https://weatherapi.com API key. Get one for free at https://www.weatherapi.com'
    required: true
  template-file:
    description: 'Template file path'
    required: true
  out-file:
    description: 'Output file path'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test }}
    - --stonks-api-key=${{ inputs.stonks-api-key }}
    - --days=${{ inputs.days }}
    - --crypto=${{ inputs.crypto }}
    - --template-file=${{ inputs.template-file }}
    - --out-file=${{ inputs.out-file }}
