name: 'Update Stonks'
description: 'Update Daily Stonks to your README.md'
inputs:
  ticker:
    description: 'Ticker'
    required: true
  days:
    description: 'Days of market'
    required: false
    default: '5'
  stonks-api-key:
    description: 'https://brapi.dev/api API key. Get one for free at https://brapi.dev/api'
    required: true
  template-file:
    description: 'Template file path'
    required: true
  out-file:
    description: 'Output file path'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test }}
    - --stonks-api-key=${{ inputs.stonks-api-key }}
    - --days=${{ inputs.days }}
    - --ticker=${{ inputs.ticker }}
    - --template-file=${{ inputs.template-file }}
    - --out-file=${{ inputs.out-file }}
